id: P000335
initial_creation_type: ocr
created_at: 13/03/2020
last_modified_at: 2021-12-16 15:34:36.784606
source_metadata:
  id: bdr:W1KG8823
  title: དགོངས་གཏེར་བཀའ་ཐང་དང་དེའི་འགྲེལ་པ།
  author: ''
  volumes:
    0720945eaf914b29b299758f203a6cdd:
      image_group_id: I1KG8873
      title: Volume 1 of dgongs gter bka' thang dang de'i 'grel pa
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
